//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormulaEditor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ED_KPI_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ED_KPI_INFO()
        {
            this.ED_KPI_VALUE = new HashSet<ED_KPI_VALUE>();
            this.EP_KPI_PARAM = new HashSet<EP_KPI_PARAM>();
            this.EP_KPI_SET = new HashSet<EP_KPI_SET>();
        }
    
        public int KPI_ID { get; set; }
        public string SD_CODE { get; set; }
        public string KPI_CODE { get; set; }
        public string KPI_NAME { get; set; }
        public string KPI_ALIAS { get; set; }
        public string KPI_TYPE_CODE { get; set; }
        public Nullable<int> ORDER_NO { get; set; }
        public string UPD_USER_ID { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ED_KPI_VALUE> ED_KPI_VALUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EP_KPI_PARAM> EP_KPI_PARAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EP_KPI_SET> EP_KPI_SET { get; set; }
    }
}
