//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormulaEditor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EP_KPI_SET
    {
        public int ID { get; set; }
        public Nullable<int> KPI_ID { get; set; }
        public string KPI_DESC { get; set; }
        public string NUM_FORMULA { get; set; }
        public string FRA_FORMULA { get; set; }
        public Nullable<int> INVALID_FLAG { get; set; }
        public string UPD_USER_ID { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    
        public virtual ED_KPI_INFO ED_KPI_INFO { get; set; }
    }
}
