//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormulaEditor.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HJSDR_BJXH_20170303_TESTEntities : DbContext
    {
        public HJSDR_BJXH_20170303_TESTEntities()
            : base("name=HJSDR_BJXH_20170303_TESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ED_KPI_INFO> ED_KPI_INFO { get; set; }
        public virtual DbSet<ED_KPI_VALUE> ED_KPI_VALUE { get; set; }
        public virtual DbSet<EP_KPI_PARAM> EP_KPI_PARAM { get; set; }
        public virtual DbSet<EP_KPI_SET> EP_KPI_SET { get; set; }
        public virtual DbSet<SD_CPATS> SD_CPATS { get; set; }
        public virtual DbSet<SD_INFO> SD_INFO { get; set; }
        public virtual DbSet<SD_ITEM_INFO> SD_ITEM_INFO { get; set; }
    }
}
