//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormulaEditor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_CPATS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_CPATS()
        {
            this.ED_KPI_VALUE = new HashSet<ED_KPI_VALUE>();
        }
    
        public string SD_CPAT_NO { get; set; }
        public string SD_CODE { get; set; }
        public System.DateTime SD_CPAT_DATE { get; set; }
        public string PATIENT_ID { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ED_KPI_VALUE> ED_KPI_VALUE { get; set; }
    }
}
