//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormulaEditor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SD_INFO()
        {
            this.SD_ITEM_INFO = new HashSet<SD_ITEM_INFO>();
        }
    
        public string SD_CODE { get; set; }
        public string SD_NAME { get; set; }
        public string SD_ALIAS { get; set; }
        public Nullable<int> ORDER_NO { get; set; }
        public int SC_FLAG { get; set; }
        public int EV_FLAG { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SD_ITEM_INFO> SD_ITEM_INFO { get; set; }
    }
}
